{% set name = "mpl-multitab" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 308a8ac5f2758a0249cc8300dfa690941ca12e433aacb1884859a70f8d4ba6a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy
    - matplotlib
    - loguru
    - pyqt

test:
  imports:
    - mpl_multitab  # [not linux]
  commands:
    - pip check
    - xvfb-run --auto-servernum python -c "import mpl_multitab"  # [linux]
  requires:
    - pip

about:
  home: https://github.com/astromancer/mpl-multitab
  summary: Tabbed figure manager for matplotlib using pyQt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
